### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by Jwiggiff** [MacArts/MacArts#1]
![image](https://user-images.githubusercontent.com/18373514/108416804-354f8300-71fd-11eb-82f0-acc1f998032d.png)

**Comment by dulldesk** [comment]
Do we still need a contact page? Since each of the department pages have contact info there anyways. 
On a similar note, is a department page needed for the central council?

**Comment by Jwiggiff** [comment]
No I don't think so. In terms of central council maybe ask in the group chat?
