### ISSUE TITLE
Navigation Bar Logo disappears

### ISSUE THREAD

**Issue by dulldesk** [MacArts/MacArts#22]
The element is there, of course, but it seems to have no width

![image](https://user-images.githubusercontent.com/54601393/122649401-a8a9c880-d0fb-11eb-9c72-774eaee57d0f.png)

**Comment by Jwiggiff** [comment]
Where/when does this happen?

**Comment by dulldesk** [comment]
On my device it happens on any viewport greater than the breakpoint when the nav bar collapses.

**Comment by Jwiggiff** [comment]
Hmmm that's weird. Doesn't happen for me. Did you try Ctrl+Shift+R?

**Comment by dulldesk** [comment]
Yea, it still doesn't appear. Quite strange indeed, as it used to sometimes appear for me as well iirc.

**Comment by Jwiggiff** [comment]
What browser are you using and what version?

**Comment by dulldesk** [comment]
Firefox 89.0.2 (Windows)
